In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('Social_Network_Ads.csv')

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
data.isnull().any()

User ID            False
Gender             False
Age                False
EstimatedSalary    False
Purchased          False
dtype: bool

In [5]:
data_new=data.drop('User ID',axis=1)

In [6]:
data_new.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [7]:
# one hot encoding of categorical coulmns
data_new.columns

Index(['Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [8]:
X=data_new.drop('Purchased',axis=1)
X.head()

Gender  Age  EstimatedSalary
0    Male   19            19000
1    Male   35            20000
2  Female   26            43000
3  Female   27            57000
4    Male   19            76000

In [9]:
y=data_new['Purchased']
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

# Observe any Categorical and change into one hot encoding

In [10]:
X.shape

(400, 3)

# Encoding gender column

In [12]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
X.iloc[:,0]=lb.fit_transform(X.iloc[:,0])


In [13]:
from scipy import stats
z=np.abs(stats.zscore(X))
z

array([[1.02020406, 1.78179743, 1.49004624],
       [1.02020406, 0.25358736, 1.46068138],
       [0.98019606, 1.11320552, 0.78528968],
       ...,
       [0.98019606, 1.17910958, 1.46068138],
       [1.02020406, 0.15807423, 1.07893824],
       [0.98019606, 1.08359645, 0.99084367]])

In [14]:
X.shape

(400, 3)

# Training the model

In [17]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train=sc.fit_transform(X_train)
X_test= sc.transform(X_test)

C:\python\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\python\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\python\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int32, int64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.


# Neural Network starts

In [19]:
import keras
from keras.models import Sequential #is used to initalize the model
from keras.layers import Dense #is used to build layers

Using TensorFlow backend.


In [20]:
model= Sequential()   # FIRST INTIALIZE YOUR MODEL

In [21]:
X_train.shape

(320, 3)

In [22]:
y_test.shape

(80,)

In [23]:
#inputlayer+hidden layer 1
model.add(Dense(input_dim=3,init="random_uniform",output_dim=50,activation='relu'))

C:\python\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=3, activation="relu", units=50, kernel_initializer="random_uniform")`
  


In [24]:
model.add(Dense(output_dim=50,init="random_uniform",activation='relu'))#hidden layer 2

C:\python\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=50, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [25]:
#output layer
model.add(Dense(output_dim=1,activation='sigmoid',init="random_uniform"))

C:\python\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  


In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 50)                200       
_________________________________________________________________
dense_2 (Dense)              (None, 50)                2550      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 2,801
Trainable params: 2,801
Non-trainable params: 0
_________________________________________________________________


In [27]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [28]:
model.fit(X_train,y_train,epochs=100,batch_size=32)


Epoch 1/100
320/320 [==============================] - 1s 2ms/step - loss: 0.6914 - accuracy: 0.6125
Epoch 2/100
320/320 [==============================] - 0s 100us/step - loss: 0.6862 - accuracy: 0.6281
Epoch 3/100
320/320 [==============================] - 0s 100us/step - loss: 0.6744 - accuracy: 0.6812
Epoch 4/100
320/320 [==============================] - 0s 125us/step - loss: 0.6509 - accuracy: 0.7500
Epoch 5/100
320/320 [==============================] - 0s 125us/step - loss: 0.6103 - accuracy: 0.7875
Epoch 6/100
320/320 [==============================] - 0s 100us/step - loss: 0.5516 - accuracy: 0.8062
Epoch 7/100
320/320 [==============================] - 0s 100us/step - loss: 0.4857 - accuracy: 0.8125
Epoch 8/100
320/320 [==============================] - 0s 125us/step - loss: 0.4299 - accuracy: 0.8219
Epoch 9/100
320/320 [==============================] - 0s 100us/step - loss: 0.3866 - accuracy: 0.8313
Epoch 10/100
320/320 [==============================] - 0s 100us/step - lo

320/320 [==============================] - 0s 100us/step - loss: 0.2345 - accuracy: 0.9094
Epoch 79/100
320/320 [==============================] - 0s 100us/step - loss: 0.2351 - accuracy: 0.9094
Epoch 80/100
320/320 [==============================] - 0s 125us/step - loss: 0.2346 - accuracy: 0.9125
Epoch 81/100
320/320 [==============================] - 0s 75us/step - loss: 0.2353 - accuracy: 0.9031
Epoch 82/100
320/320 [==============================] - 0s 100us/step - loss: 0.2334 - accuracy: 0.9062
Epoch 83/100
320/320 [==============================] - 0s 75us/step - loss: 0.2331 - accuracy: 0.9125
Epoch 84/100
320/320 [==============================] - 0s 100us/step - loss: 0.2344 - accuracy: 0.9156
Epoch 85/100
320/320 [==============================] - 0s 100us/step - loss: 0.2346 - accuracy: 0.9125
Epoch 86/100
320/320 [==============================] - 0s 100us/step - loss: 0.2328 - accuracy: 0.9094
Epoch 87/100
320/320 [==============================] - 0s 100us/step - loss: 0

In [29]:
y_pred=model.predict(X_test)
y_pred

array([[8.9143932e-02],
       [7.4647069e-03],
       [7.7516139e-02],
       [1.3451934e-02],
       [2.0289421e-03],
       [2.5361776e-05],
       [2.9426813e-04],
       [9.7466791e-01],
       [7.5072050e-05],
       [8.1121171e-01],
       [3.3926964e-04],
       [2.2333860e-04],
       [8.1360042e-03],
       [2.5737232e-01],
       [3.3192635e-03],
       [8.4133887e-01],
       [1.6826165e-01],
       [2.1108091e-03],
       [8.6827129e-01],
       [3.4655631e-03],
       [1.7643273e-03],
       [9.1773057e-01],
       [4.8875004e-02],
       [9.0331209e-01],
       [5.2154064e-06],
       [9.0739954e-01],
       [2.3777902e-02],
       [2.4249434e-02],
       [9.1544688e-03],
       [6.4901948e-02],
       [6.0544312e-03],
       [2.1076119e-01],
       [9.4194865e-01],
       [6.1174929e-03],
       [1.8298626e-04],
       [1.2099743e-05],
       [2.9305816e-03],
       [1.0667145e-03],
       [2.4497509e-04],
       [8.4932256e-01],
       [4.0822685e-02],
       [5.736634

In [33]:
y_pred[0]

array([0.08914393], dtype=float32)

In [34]:
y_test[0]

KeyError: 0

In [31]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))


ValueError: Classification metrics can't handle a mix of binary and continuous targets